# apiVersion: v1
# kind: ConfigMap
# metadata:
#   name: bank-backend-config
# data:
#   DB_HOST: "production-mysql-db.csf2ue80aaqe.us-east-1.rds.amazonaws.com"
#   DB_PORT: "3306"
#   DB_NAME: "production_db"