apiVersion: v1
kind: Service
metadata:
  name: bank-backend-service
spec:
  selector:
    app: bank-backend
  ports:
    - protocol: TCP
      port: 8080   # The service port exposed internally
      targetPort: 8000  # Container port where your Spring Boot app listens
  type: LoadBalancer
